import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import clarityTheme from "./theme/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={clarityTheme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
